# Generated by Django 4.1.7 on 2023-03-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='typeuser',
        ),
    ]
