# Generated by Django 4.1.7 on 2023-03-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
